### ISSUE TITLE
Compile Issues with Python 3.7

### ISSUE THREAD

**Issue by grohup** [voxel51/eta#167]
cannot install external dependencies when using a python 3.7 environment due to cython compilation errors. 

Cython==0.25.2

checking the Cython logs, they have a fix for python 3.7 compile issues in 0.28

**Comment by brimoor** [comment]
Thanks for letting us know- I updated to `Cython==0.28.5`

**Comment by jasoncorso** [comment]
This remains an issue.   However, there is now an updated numpy (1.15) that seems to work with python 3.7.
Noting that installation process with python 3.7 (at least on OSX with brew) currently requires manual intervention at a few places.

**Comment by jasoncorso** [comment]
Manual install of `numpy`, `scipy`, `scikit-learn` and then 

`python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl`

For tensorflow.

**Comment by brimoor** [comment]
Python 3.7 is very new and it does not seem desirable that we must use an old version of Tensorflow (`0.12.0` while latest is `1.4+`) in order to support Python 3.7.

I strongly recommend that Python 3 users stick with Python 3.6 for now.

https://github.com/tensorflow/tensorflow/issues/17022
